# Generated by Django 6.0.2 on 2026-03-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_adv_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Көргендер саны'),
        ),
    ]
